import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AlertProvider from '@/components/common/alertProvider';
import { AuthProvider } from "@/contexts/authContext";
import RouteGuard from '@/components/guards/routeGuard';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Crud App",
  description: "Generated by ravihansa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AlertProvider></AlertProvider>
        <AuthProvider>
          <RouteGuard>
            {children}
          </RouteGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
